# https://hub.docker.com/r/atlassian/confluence-server

image:
  repository: atlassian/confluence-server
  tag: 6.9.0
  pullPolicy: IfNotPresent

confluence:
  reverseProxyHost: confluence.fago-labs.club
  reverseProxyPort: 8090
  reverseProxyScheme: http
  javaHeapSize: 2048m
  javaMemoryOptions: "-XX:MaxMetaspaceSize=512m -XX:MaxDirectMemorySize=512m"
  javaOptions: ""

synchrony:
  ## disable Synchrony by default
  javaHeapSize: 1024m

service:
  type: ClusterIP
  port: 8090

domain: confluence.fago-labs.club 

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - confluence.fago-labs.club
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  # existingClaim: existing-pvc

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
