apiVersion: v1
kind: Service
metadata:
  name: {{ template "atlassian-confluence.fullname" . }}
  labels:
    app: {{ template "atlassian-confluence.name" . }}
    chart: {{ template "atlassian-confluence.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090 
      protocol: TCP
      name: http
    - port: 8091
      targetPort: 8091 
      protocol: TCP
      name: synchrony
  selector:
    app: {{ template "atlassian-confluence.name" . }}
    release: {{ .Release.Name }}
